import { mkdir, writeFile } from "fs/promises";
import { join } from "path";

export interface ProjectScaffoldOptions {
  targetDir: string;
  projectName: string;
  includedSkillIds?: string[];
  includedRuleIds?: string[];
}

const DEFAULT_RULES = [
  "blocking-rules",
  "work-mode",
  "capability-evolution",
  "coding",
  "engineering-workflows",
  "testing",
  "git",
  "security",
];

const DEFAULT_SKILLS = [
  "code-review-expert",
  "testing-expert",
  "documentation-expert",
  "refactoring-expert",
  "frontend-expert",
  "backend-expert",
];

export async function createProjectScaffold(options: ProjectScaffoldOptions): Promise<string[]> {
  const rules = options.includedRuleIds ?? DEFAULT_RULES;
  const skills = options.includedSkillIds ?? DEFAULT_SKILLS;
  const created: string[] = [];

  const claudeDir = join(options.targetDir, ".claude");
  const rulesCoreDir = join(claudeDir, "rules", "core");
  const rulesDomainDir = join(claudeDir, "rules", "domain");
  const skillsDir = join(claudeDir, "skills");

  await mkdir(rulesCoreDir, { recursive: true });
  await mkdir(rulesDomainDir, { recursive: true });
  await mkdir(skillsDir, { recursive: true });

  const claudeMdPath = join(claudeDir, "CLAUDE.md");
  const claudeMd = `# ${options.projectName} Rules\n\n## Core Workflow\n- Plan → Confirm → Execute → Verify\n- Use TDD for new behavior changes\n- Verify UI changes visually before completion\n\n## Included Rules\n${rules.map((rule) => `- ${rule}`).join("\n")}\n\n## Included Skills\n${skills.map((skill) => `- ${skill}`).join("\n")}\n`;
  await writeFile(claudeMdPath, claudeMd, "utf-8");
  created.push(claudeMdPath);

  const settingsPath = join(claudeDir, "settings.json");
  const settings = {
    model: "opus",
    effort: "high",
    enabledSkills: skills,
    notes: "Generated by bobo template project",
  };
  await writeFile(settingsPath, JSON.stringify(settings, null, 2), "utf-8");
  created.push(settingsPath);

  for (const rule of rules) {
    const isCore = ["blocking-rules", "work-mode", "capability-evolution"].includes(rule);
    const outPath = join(isCore ? rulesCoreDir : rulesDomainDir, `${rule}.md`);
    await writeFile(outPath, `# ${rule}\n\nImported via bobo template project.\n`, "utf-8");
    created.push(outPath);
  }

  for (const skill of skills) {
    const skillDir = join(skillsDir, skill);
    await mkdir(skillDir, { recursive: true });
    const outPath = join(skillDir, "SKILL.md");
    await writeFile(outPath, `---\nid: ${skill}\ntitle: \"${skill}\"\ncategory: other\ntags: []\ntriggers: []\ndependencies: []\n---\n\n# ${skill}\n\nImported via bobo template project.\n`, "utf-8");
    created.push(outPath);
  }

  return created;
}
